### ISSUE TITLE
java.lang.UnsatisfiedLinkError when running `new JImGui()`

### ISSUE THREAD

**Issue by wozniak** [ice1000/jimgui#82]
This is probably something I have done wrong, but I cannot figure it out for the life of me. I am trying to use ImGui in a FabricMC minecraft mod and the game crashes on startup.

Here's the JImGui error:
```java
Caused by: java.lang.UnsatisfiedLinkError: 'long org.ice1000.jimgui.JImGui.allocateNativeObjects(int, int, long, byte[], long)'
	at org.ice1000.jimgui.JImGui.allocateNativeObjects(Native Method)
	at org.ice1000.jimgui.JImGui.<init>(JImGui.java:33)
	at org.ice1000.jimgui.JImGui.<init>(JImGui.java:38)
	at org.ice1000.jimgui.JImGui.<init>(JImGui.java:25)
	at com.wozniak.decaf.screen.ClickGuiScreen.<clinit>(ClickGuiScreen.java:10)
	at com.wozniak.decaf.mod.render.ClickGui.<clinit>(ClickGui.java:10)
	at com.wozniak.decaf.Decaf.onInitialize(Decaf.java:28)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more```

**Comment by ice1000** [comment]
Call `JniLoader.load()` before `new JImGui`

**Comment by ice1000** [comment]
Oh wow you're from Richmond! My roommate is from Richmond too LOL

**Comment by ice1000** [comment]
No response, closing
