### ISSUE TITLE
Unsupported platform

### ISSUE THREAD

**Issue by WallD3v** [ice1000/jimgui#88]
Unsupported platform 'android-aarch64', please submit issue to https://github.com/ice1000/jimgui/issues

`Unable to start activity ComponentInfo{wd.external.hack/wd.external.hack.MainActivity}: java.lang.UnsupportedOperationException: Unsupported platform 'android-aarch64', please submit issue to https://github.com/ice1000/jimgui/issues
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3770)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3907)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:137)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2393)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8061)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923)
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Unsupported platform 'android-aarch64', please submit issue to https://github.com/ice1000/jimgui/issues
                                                                                                    	at org.ice1000.jimgui.util.JniLoader.load(JniLoader.java:131)
                                                                                                    	at wd.external.hack.MainActivity.Start(MainActivity.java:170)
                                                                                                    	at wd.external.hack.MainActivity.onCreate(MainActivity.java:187)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8328)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8307)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3907) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:137) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2393) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8061) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923) 
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Native library libjimgui-aarch64-android.so not found.
                                                                                                    	at org.ice1000.jimgui.util.NativeUtil.loadLibraryFromJar(NativeUtil.java:67)
                                                                                                    	at org.ice1000.jimgui.util.JniLoader.loadLib(JniLoader.java:140)
                                                                                                    	at org.ice1000.jimgui.util.JniLoader.load(JniLoader.java:128)
                                                                                                    	at wd.external.hack.MainActivity.Start(MainActivity.java:170) 
                                                                                                    	at wd.external.hack.MainActivity.onCreate(MainActivity.java:187) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8328) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8307) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3750) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3907) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:137) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2393) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8061) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:923) `

**Comment by ice1000** [comment]
Android support is not available. I don't know how to do it
